### PR TITLE
Update instances.json | add image to my instance

### PR DESCRIPTION
**Pull request by Denisbg2011game**

### CODE REVIEW

**Comment by Denisbg2011game** [comment]
@Flam3rboy can you review this and commit it

**Comment by Denisbg2011game** [comment]
`***Hello?***`

**Comment by Denisbg2011game** [comment]
***`@Flam3rboy???`***

**Comment by Denisbg2011game** [comment]
***`@Flam3rboy are you reviewing this or someone else is`***

**Comment by Flam3rboy** [comment]
You will get blocked from contributing for spamming.

**Comment by Denisbg2011game** [comment]
> You will get blocked from contributing for spamming.

no please! i stop i go do something else okok

**Pull request closed without merging**
