### PR TITLE
Removing inactive instances

### PR DESCRIPTION
**Pull request by Iced-Coded**
This pull requests is removing every inactive instances that cannot be accessed (e.g. TheArcaneBronny - 502 Error, H3RDP0RT4L - isn't accessible + marked as dangerous by google (viewed by Firefox))

### CODE REVIEW

**Review by TheArcaneBrony — APPROVED** [review]

**Comment by Austcool-Walker** [comment]
> This pull requests is removing every inactive instances that cannot be accessed (e.g. TheArcaneBronny - 502 Error, H3RDP0RT4L - isn't accessible + marked as dangerous by google (viewed by Firefox))

This is My Instance I beg to differ it runs off a tablet so its uptime is rather questionable.

**Comment by Austcool-Walker** [comment]
Do take note that the description says "will be up as much as possible."

**Comment by Iced-Coded** [comment]
> > This pull requests is removing every inactive instances that cannot be accessed (e.g. TheArcaneBronny - 502 Error, H3RDP0RT4L - isn't accessible + marked as dangerous by google (viewed by Firefox))
> 
> This is My Instance I beg to differ it runs off a tablet so its uptime is rather questionable.

Which one? I can differ it.

**Comment by Austcool-Walker** [comment]
> > > This pull requests is removing every inactive instances that cannot be accessed (e.g. TheArcaneBronny - 502 Error, H3RDP0RT4L - isn't accessible + marked as dangerous by google (viewed by Firefox))
> > 
> > 
> > This is My Instance I beg to differ it runs off a tablet so its uptime is rather questionable.
> 
> Which one? I can differ it.
N3RDP0RT4L HQ FTC it also needs edited to run on port :9999 I changed ports because I discovered Aliucord legacy uses port :3003. Also I carry my tablet to work every day since I need it for communication expect N3RDP0RT4L HQ to be down from at least 8:00 AM EST to 2:30-3:20ish EST On Certain days of the week.

**Comment by Austcool-Walker** [comment]
https://N3RDP0RT4L.duckdns.org:9999/app

**Pull request closed without merging**
