### PR TITLE
removed some instances that didnt work

### PR DESCRIPTION
**Pull request by AToska21**
I removed some instances that just outright didn't work on my PC, and some just said 400, 532, and 404.
If any of these work for you guys, feel free to contact me.

P.S. I will keep this in draft mode until each one of these is confirmed not to work. Using ethernet with Google Chrome latest version. No firewall.

### CODE REVIEW

**Comment by AToska21** [comment]
bro rlly? Did no one notice this?

**Comment by ChrisChrome** [comment]
Will review now, sorry. A lot of stuff has been going on recently

**Review by ChrisChrome — APPROVED** [review]
I haven't checked if anything has been left out, but did confirm that all the listed removals are correct

**Comment by TheArcaneBrony** [comment]
lgtm

**Review by TheArcaneBrony — APPROVED** [review]
lgtm

**Pull request merged**
