### PR TITLE
add my instance | Update instances.json

### PR DESCRIPTION
**Pull request by Denisbg2011game**
heres a invite https://denisfosscord.run-eu-central1.goorm.io/invite/QopGSU
show peoplr this invite when they click on it

### CODE REVIEW

**Comment by Denisbg2011game** [comment]
i add instance

**Comment by Denisbg2011game** [comment]
@fosscord

**Review by Denisbg2011game — COMMENTED** [review]
i made link to be my fosscord server

**Comment by Denisbg2011game** [comment]
also will my instance appear when the webserver you have restarts?

**Comment by Denisbg2011game** [comment]
@Flam3rboy i want to ask when will it appear in the instances webpage im just asking 
~~`con`~~

**Comment by Flam3rboy** [comment]
When it gets build and deployed again. Usually every 24 hours.

**Comment by Denisbg2011game** [comment]
ok good
its not up right now so good :/

**Comment by Denisbg2011game** [comment]
do i close this?

**Comment by Denisbg2011game** [comment]
oh its clossd
i think i can lcose it again though

**Comment by Denisbg2011game** [comment]
also flam3rboy do you have any super pre release builds like preprepreprealpha i can test?

**Comment by Flam3rboy** [comment]
@Denisbg2011game https://docs.fosscord.com/setup/server/

**Pull request merged**
