### PR TITLE
Added My Instance.

### PR DESCRIPTION
**Pull request by Austcool-Walker**
Added My N3RDP0RT4L HQ Fosscord Instance to the Instances.json List.

### CODE REVIEW

**Comment by MaddyUnderStars** [comment]
you have a typo in your description ( "othwr" ) and your image is a 404

**Comment by Austcool-Walker** [comment]
> you have a typo in your description ( "othwr" ) and your image is a 404
I just noticed it and I pushed a fix? Should I open another request with those changes? I'm sorry if this sounds like a stupid question I don't pull request on GitHub or gitlab much...

**Comment by MaddyUnderStars** [comment]
No, what you did was correct. I don't have write permissions on this repo so you'll have to wait a bit

**Comment by greysilly7** [comment]
Just a warning your branch is 13 commits behind

**Comment by Austcool-Walker** [comment]
@TheArcaneBrony When you can please review and merge my pull request good sir.

**Comment by TheArcaneBrony** [comment]
can you re-open a new PR, so we dont have the rebase conflicts?

**Pull request closed without merging**
