### PR TITLE
Update instances.json

### PR DESCRIPTION
**Pull request by ImAaronFR**
Removed (1) invalid instance and updated my instance's URL

### CODE REVIEW

**Review by omxpro — CHANGES_REQUESTED** [review]
My instance is up but the thing I use for URL forwarding just shitted it's pants, here is the instance URL http:/173.208.153.242:1131 please update the pr

**Comment by ImAaronFR** [comment]
> My instance is up but the thing I use for URL forwarding just shitted it's pants, here is the instance URL http://173.208.153.242:1131 please update the pr
refused

Doesn't work

**Comment by omxpro** [comment]
Should be up now

**Comment by omxpro** [comment]
Wait no wtf
Screenshot_20211229-213308_Brave

**Comment by ImAaronFR** [comment]
> Should be up now

still connection refused (if your instance isn't 24/7 i recommend removing it from instances.json)

**Comment by omxpro** [comment]
> > Should be up now
> 
> still connection refused (if your instance isn't 24/7 i recommend removing it from instances.json)

Yeah no it is 24/7 but "small" outages happen like above, why tf does it say there is no package.json

**Comment by ImAaronFR** [comment]
> > > Should be up now
> > 
> > 
> > still connection refused (if your instance isn't 24/7 i recommend removing it from instances.json)
> 
> Yeah no it is 24/7 but "small" outages happen like above, why tf does it say there is no package.json

hmmm u sure u are in the right folder?...

**Comment by omxpro** [comment]
I think so

**Comment by omxpro** [comment]
I might have to reinstall the whole source, well gtg rn its night time and time to sleep

**Pull request merged**
