### PR TITLE
Eviecord

### PR DESCRIPTION
**Pull request by shakyevan444**
My server!

### CODE REVIEW

**Comment by shakyevan444** [comment]
uh what do i do??

**Comment by Puyodead1** [comment]
> uh what do i do??

wait

**Comment by shakyevan444** [comment]
i have 😭

**Comment by Puyodead1** [comment]
> i have sob

not long enough.

**Comment by shakyevan444** [comment]
4 days ago

**Comment by Puyodead1** [comment]
> 4 days ago

n o t    l o n g   e n o u g h

**Comment by shakyevan444** [comment]
okayyyyyy

**Comment by Puyodead1** [comment]
> okayyyyyy

ur instance is dead anyways lol

**Comment by shakyevan444** [comment]
again, cuz the person hosting it had an earthquake AND is asleep

**Comment by Puyodead1** [comment]
> again, cuz the person hosting it had an earthquake AND is asleep

well, I didnt see that message, all i saw was 'bro'

**Comment by shakyevan444** [comment]
i will eat your face off

**Comment by MaddyUnderStars** [comment]
gonna close this, because merge conflicts. feel free to reopen one. although, I'd prefer if your domain was not marked as deceptive.

**Pull request closed without merging**
