### PR TITLE
Update instances.json ()

### PR DESCRIPTION
**Pull request by Denisbg2011game**

### CODE REVIEW

**Comment by Denisbg2011game** [comment]
this pull adds my instance

**Comment by Denisbg2011game** [comment]
bug: web client dosent work with attached gifs/images, 
how to fix: use [desktop client](http://denisbed.cf/WebCord.zip)

**Comment by Denisbg2011game** [comment]
> bug: web client dosent work with attached gifs/images, how to fix: use [desktop client](http://denisbed.cf/WebCord.zip)

files work though

**Comment by TheArcaneBrony** [comment]
Is your instance still up? (ERR_ADDR_UNREACHABLE)

**Comment by Denisbg2011game** [comment]
> Is your instance still up? (ERR_ADDR_UNREACHABLE)

MAINTENANCE, excuses but im working on a new one and i kinda abbondand that
so i will creat new pull so i am close with commect

**Review by Denisbg2011game — COMMENTED** [review]
nice lol i revicew myself

**Pull request closed without merging**
