### PR TITLE
add image

### PR DESCRIPTION
**Pull request by Denisbg2011game**
Heeey guys heres my website (it up when image is up)
https://denis.run-eu-central1.goorm.io/

### CODE REVIEW

**Comment by TimSchweiz** [comment]
i think the link at your pull request shouldn't be a invite.

**Comment by Denisbg2011game** [comment]
Well it should as it is my own instance and I can do whatever with my instance

**Comment by Stilic** [comment]
Also your instance is down.

**Comment by xNaCly** [comment]
instance is down

**Comment by Denisbg2011game** [comment]
can you accept that I do not have a way of running it
As I do not have a Linux machine I only used the goormio as a port forward to hide my ip but I will get the server running in a vm

**Comment by Stilic** [comment]
Goorm is a IDE, not a hosting service.

**Comment by Denisbg2011game** [comment]
Yes yes but I used a program to port forward my ip to the goomr container and I used their ip with their container but the webserver is on my PC and I basically used a container from goormide so I can hide my ip, I'm currently setting up a Kali vm on my PC and i will try to run it 24/7

**Comment by Thesourtimes** [comment]
Why would you even use kali? Use a normal distribution instead. CentOS, Debian and Ubuntu can be some of good examples for a server.

**Comment by Denisbg2011game** [comment]
no

**Comment by Denisbg2011game** [comment]
I want to use kali

**Comment by Denisbg2011game** [comment]
only noob use Ubuntu server, joking for a reason but still those distros won't work for what I do

**Comment by Denisbg2011game** [comment]
Also your kinda right I probably won't use even half of the offensive security stuff Kali has but I will use it ANYWAY

**Comment by Thesourtimes** [comment]
Kali Linux or literally any other program/DE theme bundle distribution are just Debian, Ubuntu, Arch or SUSE bloated with unneeded components. Kali as a "Hacker" distro is most ironic and obsolete example out there. If you plan to use Linux for a daily driver, start with something like Endeavour, Mint, Fedore, Ubuntu etc. but not something like Kali or Islamic Ubuntu. For server purposes I made my suggestions above.

**Comment by Thesourtimes** [comment]
As a note: Almost 80% of the tools on Kali repositories are 15 years old broken tools with no modern purpose. For the rest, you can install any of them on any distro you wish.

**Comment by Denisbg2011game** [comment]
I just added the php repostitory and installed it and it's running and now I'm only left to open it to the internet

**Comment by Denisbg2011game** [comment]
grfhdhg

**Comment by Stilic** [comment]
It's going offtopic @Denisbg2011game.

@Flam3rboy Please close this PR as the server of this instance is a Goorm IDE shared server and not a real server.

**Comment by Denisbg2011game** [comment]
no it isn't I deleted the inefficient goormide and I'm setting up my vm so I can host it on my pc

**Comment by Denisbg2011game** [comment]
I'm working on it just wait

**Comment by Denisbg2011game** [comment]
it will be up in like about an hour and it will have a different domain

**Comment by xNaCly** [comment]
Offtopic conversation + not working contribution

**Comment by Denisbg2011game** [comment]
It's up locally yay

**Comment by Thesourtimes** [comment]
Please use comments in purpose and do not spam them. yays shouldn't fill whole #gitlog

**Comment by TheArcaneBrony** [comment]
Please don't make a PR if your instance doesn't work. This also isn't a discussion place for distro wars.

**Comment by Denisbg2011game** [comment]
I'm not making a war between Linux distros, I just said I made a vm with Kali Linux and that's it

**Pull request closed without merging**
