### PR TITLE
add my instance

### PR DESCRIPTION
**Pull request by AToska21**

### CODE REVIEW

**Comment by omxpro** [comment]
What's edited in this?

**Comment by AToska21** [comment]
i added my fosscord instance? isnt that what this repo is?

**Comment by ChrisChrome** [comment]
> What's edited in this?

Why are you asking what's changed? Just click on the commit

**Comment by omxpro** [comment]
> > What's edited in this?
> 
> Why are you asking what's changed? Just click on the commit

I am asking thus cuz of the description say8ng heavyly edited

**Comment by ChrisChrome** [comment]
> > > What's edited in this?
> 
> > 
> 
> > Why are you asking what's changed? Just click on the commit
> 
> 
> 
> I am asking thus cuz of the description say8ng heavyly edited

Where does it say that? I just looked at the two commits and it's literally adding a single instance to the bottom, and that second one is just fixing a missing comma

**Comment by omxpro** [comment]
Screenshot_20211219-085134_Brave

**Comment by omxpro** [comment]
Screenshot_20211219-085305_Brave

**Comment by Thesourtimes** [comment]
This isn't a fosscord Instance, It's a minecraft server's panel.

**Comment by AToska21** [comment]
Shit sorry forgot 3001

**Comment by omxpro** [comment]
> Shit sorry forgot 3001

Screenshot_20211219-153001_Brave

**Comment by AToska21** [comment]
its not ssl

> > Shit sorry forgot 3001
> 
> Screenshot_20211219-153001_Brave

**Comment by ChrisChrome** [comment]
> its not ssl
> 
> > > Shit sorry forgot 3001

You should really set up Nginx reverse proxy for both of those issues, SSL and changing the port, hmu on the Fosscord Discord server if you need help

**Review by omxpro — CHANGES_REQUESTED** [review]
Change https:// to http://

**Comment by rflrkn** [comment]
You know it doesn’t really work like that? Stuff doesn’t automatically get SSL-encrypted just by changing `http://` to `https://`.

In this case, you’d need to set up a reverse proxy (using Nginx or Apache) with a valid certificate. This would also allow you to omit the port number from the URL. 
There are tons of tutorials online on how to do stuff like this properly.

**Comment by AToska21** [comment]
> > its not ssl
> > > > Shit sorry forgot 3001
> 
> You should really set up Nginx reverse proxy for both of those issues, SSL and changing the port, hmu on the Fosscord Discord server if you need help

tag?

**Comment by AToska21** [comment]
> You know it doesn’t really work like that? Stuff doesn’t automatically get SSL-encrypted just by changing `http://` to `https://`.
> 
> In this case, you’d need to set up a reverse proxy (using Nginx or Apache) with a valid certificate. This would also allow you to omit the port number from the URL. There are tons of tutorials online on how to do stuff like this properly.

I know. I have experience with Apache2. I HAD setup SSL, but it wouldn't load. It just got stuck in the "loading".

**Comment by AToska21** [comment]
ready for merging- wait

**Comment by AToska21** [comment]
now its ready

**Comment by rflrkn** [comment]
Bad Gateway…

**Comment by AToska21** [comment]
huh? oh right i forgot to start the service

**Comment by omxpro** [comment]
Awnser this- what is so heavily edited?

Screenshot_20211219-085305_Brave
@AToska21

**Comment by AToska21** [comment]
> Awnser this- what is so heavily edited?
> 
> 
> 
> Screenshot_20211219-085305_Brave
> 
> @AToska21 

It's a description. And by heavily edited I mean added some new features.

**Comment by omxpro** [comment]
> > Awnser this- what is so heavily edited?
> > Screenshot_20211219-085305_Brave
> > @AToska21
> 
> It's a description. And by heavily edited I mean added some new features.

What are the new features?

**Comment by AToska21** [comment]
> > > Awnser this- what is so heavily edited?
> 
> > > Screenshot_20211219-085305_Brave
> 
> > > @AToska21
> 
> > 
> 
> > It's a description. And by heavily edited I mean added some new features.
> 
> 
> 
> What are the new features?

Fine, complainer. I'll change it.

**Comment by omxpro** [comment]
Sorry for complaining too much, but heavily is only used if you edited the whole server like a rewrite, I am sorry again, you shall allways tell the truth in description's

**Pull request merged**
