### PR TITLE
fix invalid json

### PR DESCRIPTION
**Pull request by Puyodead1**
:husk:

### CODE REVIEW

**Comment by greysilly7** [comment]
What exactly was invalid?

**Comment by TheArcaneBrony** [comment]
@greysilly7 leading comma

**Comment by Puyodead1** [comment]
> What exactly was invalid?

leading comma, js rejects parsing it

**Comment by greysilly7** [comment]
Ah

**Comment by TheArcaneBrony** [comment]
oh, i just noticed you replaced tabs with commas :skull:

**Comment by Austcool-Walker** [comment]
@TheArcaneBrony @Puyodead1 @greysilly7 thanks for fixing that if I knew that the formating broke native react I would
have fixed it myself to save you guys headache. I also wanted to say that I'm happy to share my instance as a option on
https://fosscord.com do to so many instances being down. I hope many people will PR to add instances to the
Community Instances helps us so when we get confederation support. (Muti Instances communicating with each other.)

**Comment by Puyodead1** [comment]
> @TheArcaneBrony @Puyodead1 @greysilly7 thanks for fixing that if I knew that the formating broke native react I would have fixed it myself to save you guys headache. I also wanted to say that I'm happy to share my instance as a option on https://fosscord.com do to so many instances being down. I hope many people will PR to add instances to the Community Instances helps us so when we get confederation support. (Muti Instances communicating with each other.)

No problem, it's not that big of a deal since it's just me developing stuff with the app. :P

**Pull request merged**
