### PR TITLE
Add A New Instance

### PR DESCRIPTION
**Pull request by greysilly7**
This adds an instance that I and TheArcaneBrony spent an hour on.

### CODE REVIEW

**Comment by greysilly7** [comment]
Horny No More

**Comment by evlyou666** [comment]
what with the image why?

**Comment by greysilly7** [comment]
What about thge image?

**Comment by MaddyUnderStars** [comment]
remove mention of discord

**Comment by greysilly7** [comment]
FUCK WRONG TEXT

**Comment by TheArcaneBrony** [comment]
good job you ratelimited gitlogs on the discord.com guild smh

**Comment by greysilly7** [comment]
Yay

**Comment by TheArcaneBrony** [comment]
image

**Comment by evlyou666** [comment]
> image

lol

**Comment by greysilly7** [comment]
I am sorry gitlogs R.I.P

**Comment by TheArcaneBrony** [comment]
image
this option exists...

**Comment by greysilly7** [comment]
Yup

**Comment by greysilly7** [comment]
I have used it when I spent hours debugging and tons of commits

**Pull request merged**
